### ISSUE TITLE
Trouble getting it to work

### ISSUE THREAD

**Issue by ksmithut** [matchai/ts-quick#80]
Just running a quick example, I'm unsure what I'm doing wrong:

`package.json`

```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "test": "ts-quick"
  },
  "devDependencies": {
    "ts-quick": "^1.1.15"
  }
}
```

`index.js`

```js
function square(a) {
  return a * a
}

add(1, 2)
```

After running `npm install` or `yarn` to install dependencies, I run `npm test` or `yarn test`, but I don't get any output. Am I missing something? Or is it too early in development to be testing out?

**Comment by matchai** [comment]
It looks like there was a slight hiccup when the CLI initially started.
The bug should now be fixed. 😄
